
In 2086, a one hundred and two year old Mark Zuckerberg is about to give his first public interview detailing secretive *dis-aging* research. The broadly anticipated event is beginning to start broadcasting live over 3D hologram to an audience across the world. Mark, being one of the earliest benefactors of the groundbreaking technology, is present in staunch health.

"Mark, you're ahundredandtwo but you look like you're twenty five. Will you tell us how you did it?" Jim, the unhurried interviewer, drawls.

Jim is one of the rare hosts that could exist in a moment that he knew to be so large, and still flourish in his own art form. A small lucky crowd is in attendance at the studio.

Mark already has a grin coming onto his face, "It's all in the hoodie." he smiled, perpetuating a long played out sartorial comedy that his PR team insisted he keep pushing. The audience responds softly with their expected laughter. "No, no-" (he is making a *hold-the-applause* kind of gesture) "in all honesty, I owe so much of my health to a familiar crustacean, the lobster.

"Let me explain:" he said, "people enjoy lobster for all sorts of reasons, but we like them for something called Teleomaise: a unique enzyme that spawned an entirely new field of research!" It was true, the results that his computational genetics laboratory had produced were groundbreaking.

He continues excitedly, "After examining terabytes of lobster DNA, my team of scientists have been able to make significant progress towards halting the decay of the human body, meaning we can minimize the effects of the aging process. As you know, what I'm here to discuss today is our recent discovery of the cure for cancer."

Jim leans in, "Yes, Mark, it's truly amazing work," and slowly taps a hand on Mark's shoulder. "Now... with this most recent announcement, how many *pre-cure* diseases still exist? How will this affect life expectancy metrics?"

"According to the CDC, there are two hundred and thirty seven remaining PCDs"  - *pre-cure* diseases - "and my team are working on them as we speak. There are really only 3 PCD categories left,  most of those 'diseases' are technical variants of the same root causalities. Without cancer, the remaining causalities are dermatological failure, immunodeficiency, and mental decay.

"Today almost forty percent of deaths are due to a *pre-cure* disease. After **Can Cancer** rolls out, we expect to see that number drop below ten percent." Bursts of applause break out, and hold, but Mark goes on, "The kit will contain a single syringe of fluid to be administered by a certified shot-administering bot. This will be a one-time procedure..."



[hr/]



By the end of the twenty-first century, "the talk" that parents must have with their children became considerably more complicated. It had little to do with sex, which by this time was purely dealt with online, but stemmed from a massive influx in organ replacements procedures, or *swaps*, that humanity was still trying to reckon with.

Even with all the new technology, if a person didn't die from disease or old age their body would still continue aging. At some point an organ would wear out and fail, and a swap had to be done. Initially the procedures were done with manual incisions, but society quickly figured out that surgery could be much easier with a few modifications to the humans. An organ componentization process was developed.

The process involved an immensely painful procedure and a tortoursly long recovery period. During this period one must lie very still as to not disturb any of the new equipment. Children weren't able to undergo the surgery, as it is so physically and emotionally intensive, so it had to be elected during adulthood. In practice this meant that the human torso became a litter of doors and drawers, each easily sliding away to reveal an access point to a vital organ. With the modification performing a kidney swap was like operating a Keurig.

At some point people decided that it would be a good idea if kids didn't hear about this little corporal imposition until the eve of their 18th birthday, when mom and dad would sit down and explain the situation. This shared deception eventually lead to a rite-of-passage ritual whereby on their 18th birthday, most children would elect to endure the enhancement. Parties would be held in the patient's honor, which unfortunately, they could never attend given their preoccupation with considering the immense post-op pain, and laying perfectly still on a stiff twin bed.


[hr/]

It wasn't until 2097 that the national deaths due to pre-cure disease (DDPCD) rate droped to Mark Zuckerberg's targeted 10 percent. The DDPCD had become the main metric against which the nation measured its success, this being especially important in the midst of a hostile global health race towards the promise of perpetual being. To Mr. Zuckerberg's credit, the 11 year delay didn't feel so long anymore.

After an international lobster shortage had interfered with the production of the initial **Can Cancer** kit, Zuckerberg was forced to partner with the vegan meat industry in order to grow the perfect lobster. After six years of research, they were able to grow flesh that contained the necessary enzymes.

Only thirteen months (and a massive ramping up of production) later, and cures were shipping nationwide. The laboratories used the excess meat to host cocktail parties or, in the case of one particularly strange discovery celebration, a massive vegan-lobster-meat-and-butter food fight that devolved into something of a lobster worshiping orgy.

[hr/]

Due to regulations, only Doctors could open a person's organ access gates. The protections were set up in the earnest interest of preventing abuse (mostly that pesky type associated with such devastatingly easy opportunity to terminate one's own life). Even so, thrill seekers and addicts found ways to have their fun. You think you've lived? Try pulling your heart out.  Leave it for just the right amount of time, and you've felt the rush. The average person can only pull out and ride the edge of death once or twice before they hit eject and forget to plug something back in.

It was decided that children didn't need to know about any of this, and they certainly didn't need to read the constant vitriolic ethical debates about the procedure ravaging forums on the freeweb. To protect minors from sensitive information, web browsers weren't allowed to display any reference to modular humans until after a user's 18th birthday.

Distracting links would be displayed in place of the offending conversation. These links tailored to target students' specific interests to get them off of offending sites quickly, mostly consisting of games, sports, movies, and pornography, which we decided to show them so they'd stop asking questions.

[hr/]

The last two failures of the human body to be addressed were the failures of the skin and the brain. Advances in materials science eventually made it possible to replace a body's entire covering of skin with a fabric-like substitute. For this transformation people paid dearly with a loss of sensation, but their internals would be protected forever and there was always the promise of upgrade.

Early adopters of the technology were disparagingly referred to as *blanks*, because their new skin was closer in texture to linens or blankets, and because there was still a general distrust of all the new technology. Eventually the technology became bearable and full replacement became common practice, although it never looked quite natural.

Mental decay was the more troubling problem to solve. Scientists were able to create a brain that could physically last forever, but in all of the tests the neurons would end up firing out of control, sending the system into a looping crash. It seems our consciousness just wasn't programmed to last forever.

But progress can't be stopped for long, and although science might not be able to be able to perpetuate a whole mind, it could still preserve parts of one. Those parts are enough to train a model can simply simulate the expected behavior of a person during a specific portion of their life. The preservee was able to choose which period of their mind to use, for example, one could ask for the "late twenties."

An *immutabrain* could be grown, flashed with a decision making process, and accrue new memories but never deviate in personality. Your *immutabrain* was developed, inspected, and swapped into your head; it was designed to operate into the oblivion.

[hr/]

A father and his son sat down together one night before bed, the man intending to teach the child about Heaven and Hell.

"You may not like to hear this," he started cautiously (most children were raised atheist at this time), "but Heaven and Hell are real. You will be judged for your sins at a point in your life."

The boy looks up incredulously, "God isn't real. They proved it, I checked the math."

"I'm not talking about God, I'm talking about G-O-D-. You see, when a person's mind starts to fail, a decision has to be made about whether to keep it, to let it continue, or whether to terminate it."

The Global Organization of Deciding or GOD as they were more commonly known, was charged with analyzing how a mind had lived. If they evaluated that it had lived a good life, then they would recommend continuation. Otherwise it would simply live out its course. Those that weren't chosen could still opt for a biologically upgraded brain, but eventually their mind would degenerate and be thrown into a strange chaos for the rest of time. Those chosen to be upgraded would have their mind swiftly terminated and replaced with an *immutabrain*.

A look of somber understanding came over the child. He started to cry. "They know everything I've done?! I'm in trouble! I didn't mean it - I didn't know!"

"It's okay son, they won't start the recording until you turn eighteen. There's nothing to worry about right now, but you should get in the habit of doing right. Think about this as a trial period. If you’re extra good they won’t give you a second look later on. But if you’re bad… you’ll have them following you around, keeping an eye on you for the rest of your life. Do you understand?"

"Yes sir. I never meant to do anything wrong!"

"I know. And let’s make sure we keep it that way. We all want you want to be accepted."

